const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  analyzeUrl: (url) => ipcRenderer.invoke('analyze-url', url),
  startDownload: (args) => ipcRenderer.send('start-download', args),
  cancelDownload: (id) => ipcRenderer.send('cancel-download', id),
  cancelAllDownloads: () => ipcRenderer.send('cancel-all-downloads'),
  selectDirectory: () => ipcRenderer.invoke('select-directory'),
  appQuit: () => ipcRenderer.send('app-quit'),
  checkUpdates: () => ipcRenderer.invoke('check-updates'),
  updateYtdlp: () => ipcRenderer.invoke('update-ytdlp'),
  openHomeDir: () => ipcRenderer.invoke('open-home-dir'),
  openFile: (path) => ipcRenderer.invoke('open-file', path),
  deleteFile: (path) => ipcRenderer.invoke('delete-file', path),
  showItemInFolder: (path) => ipcRenderer.invoke('show-item-in-folder', path),
  minimizeWindow: () => ipcRenderer.invoke('minimize-window'),
  toggleMaximizeWindow: () => ipcRenderer.invoke('toggle-maximize-window'),
  openExternalUrl: (url) => ipcRenderer.invoke('open-external-url', url),
  onProgress: (callback) => ipcRenderer.on('download-progress', (_event, value) => callback(value)),
  onComplete: (callback) => ipcRenderer.on('download-complete', (_event, value) => callback(value)),
  onError: (callback) => ipcRenderer.on('download-error', (_event, value) => callback(value)),
  selectImage: () => ipcRenderer.invoke('select-image'),
  selectFiles: () => ipcRenderer.invoke('select-files'),
  convertFile: (args) => ipcRenderer.send('convert-file', args),
  onConvertProgress: (callback) => ipcRenderer.on('convert-progress', (_event, value) => callback(value)),
  onConvertComplete: (callback) => ipcRenderer.on('convert-complete', (_event, value) => callback(value)),
  onConvertError: (callback) => ipcRenderer.on('convert-error', (_event, value) => callback(value)),
  getAppVersion: () => ipcRenderer.invoke('get-app-version'),
  openLogs: () => ipcRenderer.invoke('open-logs'),
  getSubscriptions: () => ipcRenderer.invoke('get-subscriptions'),
  addSubscription: (url) => ipcRenderer.invoke('add-subscription', url),
  deleteSubscription: (id) => ipcRenderer.invoke('delete-subscription', id),
  checkSubscriptionsNow: () => ipcRenderer.invoke('check-subscriptions-now'),
  installUpdate: () => ipcRenderer.invoke('install-update'),
  getDefaultDownloads: () => ipcRenderer.invoke('get-default-downloads'),
  // ── App settings (persisted to ~/.orbit/settings.json, read by the download engine) ──
  getGlobalSettings: () => ipcRenderer.invoke('get-global-settings'),
  saveGlobalSettings: (s) => ipcRenderer.invoke('save-global-settings', s),
  setLaunchAtStartup: (v) => ipcRenderer.invoke('set-launch-at-startup', v),
  getLaunchAtStartup: () => ipcRenderer.invoke('get-launch-at-startup'),
  clearTempCache: () => ipcRenderer.invoke('clear-temp-cache'),
  getCacheSize: () => ipcRenderer.invoke('get-cache-size'),
  testProxy: (proxy) => ipcRenderer.invoke('test-proxy', proxy),
  notify: (title, body) => ipcRenderer.invoke('notify', { title, body }),
  getGpus: () => ipcRenderer.invoke('get-gpus'),
  selectVideoFile: () => ipcRenderer.invoke('select-video-file'),
  getVideoFps: (path) => ipcRenderer.invoke('get-video-fps', path),
  aiInterpolate: (args) => ipcRenderer.send('ai-interpolate', args),
  onAIInterpolateProgress: (cb) => ipcRenderer.on('ai-interpolate-progress', (_e, v) => cb(v)),
  onAIInterpolateComplete: (cb) => ipcRenderer.on('ai-interpolate-complete', (_e, v) => cb(v)),
  onAIInterpolateError: (cb) => ipcRenderer.on('ai-interpolate-error', (_e, v) => cb(v)),
  checkForUpdate: () => ipcRenderer.invoke('check-for-update'),
  startUpdateDownload: () => ipcRenderer.invoke('start-update-download'),
  checkToolUpdates: () => ipcRenderer.invoke('check-tool-updates'),
  onUpdaterStatus: (cb) => ipcRenderer.on('updater-status', (_e, v) => cb(v)),
  rpcUpdate: (data) => ipcRenderer.send('rpc-update', data),
  openSniffer: (url) => ipcRenderer.send('open-sniffer', url),
  onSnifferCaughtVideo: (cb) => {
    ipcRenderer.on('sniffer-caught-video', (_e, v) => cb(v));
    return () => ipcRenderer.removeAllListeners('sniffer-caught-video');
  },
  onDownloadLog: (cb) => {
    ipcRenderer.on('download-log', (_e, v) => cb(v));
    return () => ipcRenderer.removeAllListeners('download-log');
  },
  getLogFile: () => ipcRenderer.invoke('get-log-file'),
  openChangelog: () => ipcRenderer.invoke('open-changelog'),
  openCrunchyrollSniffer: () => ipcRenderer.send('open-crunchyroll-sniffer'),
  startCrunchyrollDownload: (data) => ipcRenderer.send('start-crunchyroll-download', data),
  onCrunchyrollEpisodeDetected: (cb) => ipcRenderer.on('crunchyroll-episode-detected', (_e, v) => cb(v)),
  onCrunchyrollProgress: (cb) => ipcRenderer.on('crunchyroll-dl-progress', (_e, v) => cb(v)),
  onCrunchyrollComplete: (cb) => ipcRenderer.on('crunchyroll-dl-complete', (_e, v) => cb(v)),
  onCrunchyrollError: (cb) => ipcRenderer.on('crunchyroll-dl-error', (_e, v) => cb(v)),
  onCrunchyrollSnifferStatus: (cb) => ipcRenderer.on('crunchyroll-sniffer-status', (_e, v) => cb(v)),
  selectMediaFile: () => ipcRenderer.invoke('select-media-file'),
  transcribe: (args) => ipcRenderer.send('transcribe', args),
  onTranscribeProgress: (cb) => ipcRenderer.on('transcribe-progress', (_e, v) => cb(v)),
  onTranscribeComplete: (cb) => ipcRenderer.on('transcribe-complete', (_e, v) => cb(v)),
  onTranscribeError: (cb) => ipcRenderer.on('transcribe-error', (_e, v) => cb(v)),

  // ── Topaz Video AI ──
  topazDetect: () => ipcRenderer.invoke('topaz-detect'),
  topazSelectFiles: () => ipcRenderer.invoke('topaz-select-files'),
  topazProbe: (file) => ipcRenderer.invoke('topaz-probe', file),
  topazThumbnail: (file) => ipcRenderer.invoke('topaz-thumbnail', file),
  topazGpus: () => ipcRenderer.invoke('topaz-gpus'),
  topazGpuStats: () => ipcRenderer.invoke('topaz-gpu-stats'),
  topazPreview: (job) => ipcRenderer.invoke('topaz-preview', job),
  topazPresetsLoad: () => ipcRenderer.invoke('topaz-presets-load'),
  topazPresetsSave: (presets) => ipcRenderer.invoke('topaz-presets-save', presets),
  topazQueueLoad: () => ipcRenderer.invoke('topaz-queue-load'),
  topazQueueSave: (queue) => ipcRenderer.invoke('topaz-queue-save', queue),
  topazStart: (job) => ipcRenderer.send('topaz-start', job),
  topazCancel: (id) => ipcRenderer.send('topaz-cancel', id),
  onTopazProgress: (cb) => { ipcRenderer.on('topaz-progress', (_e, v) => cb(v)); return () => ipcRenderer.removeAllListeners('topaz-progress'); },
  onTopazComplete: (cb) => { ipcRenderer.on('topaz-complete', (_e, v) => cb(v)); return () => ipcRenderer.removeAllListeners('topaz-complete'); },
  onTopazError: (cb) => { ipcRenderer.on('topaz-error', (_e, v) => cb(v)); return () => ipcRenderer.removeAllListeners('topaz-error'); },

  // ── Orbit Enhance (moteur libre) ──
  enhanceDetect: () => ipcRenderer.invoke('enhance-detect'),
  enhanceInstall: () => ipcRenderer.invoke('enhance-install'),
  enhanceSelectFiles: () => ipcRenderer.invoke('enhance-select-files'),
  enhanceProbe: (file) => ipcRenderer.invoke('enhance-probe', file),
  enhanceThumbnail: (file) => ipcRenderer.invoke('enhance-thumbnail', file),
  enhanceGpus: () => ipcRenderer.invoke('enhance-gpus'),
  enhanceGpuStats: () => ipcRenderer.invoke('enhance-gpu-stats'),
  enhancePreview: (job) => ipcRenderer.invoke('enhance-preview', job),
  enhancePresetsLoad: () => ipcRenderer.invoke('enhance-presets-load'),
  enhancePresetsSave: (p) => ipcRenderer.invoke('enhance-presets-save', p),
  enhanceQueueLoad: () => ipcRenderer.invoke('enhance-queue-load'),
  enhanceQueueSave: (q) => ipcRenderer.invoke('enhance-queue-save', q),
  enhanceStart: (job) => ipcRenderer.send('enhance-start', job),
  enhanceCancel: (id) => ipcRenderer.send('enhance-cancel', id),
  onEnhanceProgress: (cb) => { ipcRenderer.on('enhance-progress', (_e, v) => cb(v)); return () => ipcRenderer.removeAllListeners('enhance-progress'); },
  onEnhanceComplete: (cb) => { ipcRenderer.on('enhance-complete', (_e, v) => cb(v)); return () => ipcRenderer.removeAllListeners('enhance-complete'); },
  onEnhanceError: (cb) => { ipcRenderer.on('enhance-error', (_e, v) => cb(v)); return () => ipcRenderer.removeAllListeners('enhance-error'); },

  // ── HandBrake ──
  hbDetect: () => ipcRenderer.invoke('hb-detect'),
  hbInstall: () => ipcRenderer.invoke('hb-install'),
  hbQueueLoad: () => ipcRenderer.invoke('hb-queue-load'),
  hbQueueSave: (q) => ipcRenderer.invoke('hb-queue-save', q),
  hbPresetsLoad: () => ipcRenderer.invoke('hb-presets-load'),
  hbPresetsSave: (p) => ipcRenderer.invoke('hb-presets-save', p),
  hbStart: (job) => ipcRenderer.send('hb-start', job),
  hbCancel: (id) => ipcRenderer.send('hb-cancel', id),
  onHbProgress: (cb) => { ipcRenderer.on('hb-progress', (_e, v) => cb(v)); return () => ipcRenderer.removeAllListeners('hb-progress'); },
  onHbComplete: (cb) => { ipcRenderer.on('hb-complete', (_e, v) => cb(v)); return () => ipcRenderer.removeAllListeners('hb-complete'); },
  onHbError: (cb) => { ipcRenderer.on('hb-error', (_e, v) => cb(v)); return () => ipcRenderer.removeAllListeners('hb-error'); },

  // ── Médiathèque (Anime Media Manager) ──
  libLoad: () => ipcRenderer.invoke('lib-load'),
  libSave: (data) => ipcRenderer.invoke('lib-save', data),
  libAddFiles: () => ipcRenderer.invoke('lib-add-files'),
  libScanFolder: () => ipcRenderer.invoke('lib-scan-folder'),
  libProbe: (file) => ipcRenderer.invoke('lib-probe', file),
  libThumbnail: (file) => ipcRenderer.invoke('lib-thumbnail', file),
  libParseName: (name) => ipcRenderer.invoke('lib-parse-name', name),
  libPresets: () => ipcRenderer.invoke('lib-presets'),
  libConvert: (job) => ipcRenderer.send('lib-convert', job),
  libCancel: (id) => ipcRenderer.send('lib-cancel', id),
  onLibConvertProgress: (cb) => { ipcRenderer.on('lib-convert-progress', (_e, v) => cb(v)); return () => ipcRenderer.removeAllListeners('lib-convert-progress'); },
  onLibConvertComplete: (cb) => { ipcRenderer.on('lib-convert-complete', (_e, v) => cb(v)); return () => ipcRenderer.removeAllListeners('lib-convert-complete'); },
  onLibConvertError: (cb) => { ipcRenderer.on('lib-convert-error', (_e, v) => cb(v)); return () => ipcRenderer.removeAllListeners('lib-convert-error'); },

  // ── Suppression de fond IA (Robust Video Matting) ──
  mattingDetect: () => ipcRenderer.invoke('matting-detect'),
  mattingInstall: (modelKey) => ipcRenderer.invoke('matting-install', modelKey),
  mattingPreview: (job) => ipcRenderer.invoke('matting-preview', job),
  mattingStart: (job) => ipcRenderer.send('matting-start', job),
  mattingCancel: (id) => ipcRenderer.send('matting-cancel', id),
  onMattingProgress: (cb) => { ipcRenderer.on('matting-progress', (_e, v) => cb(v)); return () => ipcRenderer.removeAllListeners('matting-progress'); },
  onMattingComplete: (cb) => { ipcRenderer.on('matting-complete', (_e, v) => cb(v)); return () => ipcRenderer.removeAllListeners('matting-complete'); },
  onMattingError: (cb) => { ipcRenderer.on('matting-error', (_e, v) => cb(v)); return () => ipcRenderer.removeAllListeners('matting-error'); },

  // ── AI Assistant ──
  aiChat: (data) => ipcRenderer.invoke('ai-chat', data),
  llmStatus: () => ipcRenderer.invoke('llm-status'),
  llmInstall: () => ipcRenderer.invoke('llm-install'),
  onLlmProgress: (cb) => { ipcRenderer.on('llm-progress', (_e, v) => cb(v)); return () => ipcRenderer.removeAllListeners('llm-progress'); },
});
