const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  analyzeUrl: (url) => ipcRenderer.invoke('analyze-url', url),
  startDownload: (args) => ipcRenderer.send('start-download', args),
  cancelDownload: (id) => ipcRenderer.send('cancel-download', id),
  cancelAllDownloads: () => ipcRenderer.send('cancel-all-downloads'),
  selectDirectory: () => ipcRenderer.invoke('select-directory'),
  appQuit: () => ipcRenderer.send('app-quit'),
  checkUpdates: () => ipcRenderer.invoke('check-updates'),
  updateYtdlp: () => ipcRenderer.invoke('update-ytdlp'),
  installDeno: () => ipcRenderer.invoke('install-deno'),
  getDenoStatus: () => ipcRenderer.invoke('get-deno-status'),
  openHomeDir: () => ipcRenderer.invoke('open-home-dir'),
  openFile: (path) => ipcRenderer.invoke('open-file', path),
  deleteFile: (path) => ipcRenderer.invoke('delete-file', path),
  showItemInFolder: (path) => ipcRenderer.invoke('show-item-in-folder', path),
  preparePlayback: (path) => ipcRenderer.invoke('prepare-playback', path),
  onPlaybackProgress: (cb) => { const h = (_e, v) => cb(v); ipcRenderer.on('playback-progress', h); return () => ipcRenderer.removeListener('playback-progress', h); },
  minimizeWindow: () => ipcRenderer.invoke('minimize-window'),
  toggleMaximizeWindow: () => ipcRenderer.invoke('toggle-maximize-window'),
  openExternalUrl: (url) => ipcRenderer.invoke('open-external-url', url),
  onProgress: (callback) => ipcRenderer.on('download-progress', (_event, value) => callback(value)),
  onComplete: (callback) => ipcRenderer.on('download-complete', (_event, value) => callback(value)),
  onError: (callback) => ipcRenderer.on('download-error', (_event, value) => callback(value)),
  selectImage: () => ipcRenderer.invoke('select-image'),
  selectFiles: () => ipcRenderer.invoke('select-files'),
  toolboxPick: (kind) => ipcRenderer.invoke('toolbox-pick', kind),
  toolboxPickMany: (kind) => ipcRenderer.invoke('toolbox-pick-many', kind),
  toolboxPickSub: () => ipcRenderer.invoke('toolbox-pick-sub'),
  toolboxTranslateSrt: (args) => ipcRenderer.invoke('toolbox-translate-srt', args),
  toolboxOcr: (args) => ipcRenderer.invoke('toolbox-ocr', args),
  toolboxSaveText: (args) => ipcRenderer.invoke('toolbox-save-text', args),
  toolboxPickFolder: () => ipcRenderer.invoke('toolbox-pick-folder'),
  toolboxPickAny: () => ipcRenderer.invoke('toolbox-pick-any'),
  toolboxRenameBatch: (args) => ipcRenderer.invoke('toolbox-rename-batch', args),
  getClipboardText: () => ipcRenderer.invoke('get-clipboard-text'),
  convertproDetect: (paths) => ipcRenderer.invoke('convertpro-detect', paths),
  convertproScan: (folder) => ipcRenderer.invoke('convertpro-scan', folder),
  convertproRun: (args) => ipcRenderer.invoke('convertpro-run', args),
  onConvertproProgress: (cb) => { const h = (_e, v) => cb(v); ipcRenderer.on('convertpro-progress', h); return () => ipcRenderer.removeListener('convertpro-progress', h); },
  aeDetect: () => ipcRenderer.invoke('ae-detect'),
  aeYearCodes: () => ipcRenderer.invoke('ae-year-codes'),
  aeRun: (args) => ipcRenderer.invoke('ae-run', args),
  aeConvertVersion: (args) => ipcRenderer.invoke('ae-convert-version', args),
  toolboxRun: (job) => ipcRenderer.invoke('toolbox-run', job),
  toolboxCancel: (jobId) => ipcRenderer.invoke('toolbox-cancel', jobId),
  toolboxWatchStart: (args) => ipcRenderer.invoke('toolbox-watch-start', args),
  toolboxWatchStop: () => ipcRenderer.invoke('toolbox-watch-stop'),
  onToolboxWatchEvent: (cb) => { const h = (_e, v) => cb(v); ipcRenderer.on('toolbox-watch-event', h); return () => ipcRenderer.removeListener('toolbox-watch-event', h); },
  onToolboxProgress: (cb) => { const h = (_e, v) => cb(v); ipcRenderer.on('toolbox-progress', h); return () => ipcRenderer.removeListener('toolbox-progress', h); },
  convertFile: (args) => ipcRenderer.send('convert-file', args),
  onConvertProgress: (callback) => ipcRenderer.on('convert-progress', (_event, value) => callback(value)),
  onConvertComplete: (callback) => ipcRenderer.on('convert-complete', (_event, value) => callback(value)),
  onConvertError: (callback) => ipcRenderer.on('convert-error', (_event, value) => callback(value)),
  getAppVersion: () => ipcRenderer.invoke('get-app-version'),
  openLogs: () => ipcRenderer.invoke('open-logs'),
  getSubscriptions: () => ipcRenderer.invoke('get-subscriptions'),
  addSubscription: (url) => ipcRenderer.invoke('add-subscription', url),
  deleteSubscription: (id) => ipcRenderer.invoke('delete-subscription', id),
  checkSubscriptionsNow: () => ipcRenderer.invoke('check-subscriptions-now'),
  installUpdate: () => ipcRenderer.invoke('install-update'),
  getDefaultDownloads: () => ipcRenderer.invoke('get-default-downloads'),
  // ── App settings (persisted to ~/.orbit/settings.json, read by the download engine) ──
  getGlobalSettings: () => ipcRenderer.invoke('get-global-settings'),
  saveGlobalSettings: (s) => ipcRenderer.invoke('save-global-settings', s),
  setLaunchAtStartup: (v) => ipcRenderer.invoke('set-launch-at-startup', v),
  getLaunchAtStartup: () => ipcRenderer.invoke('get-launch-at-startup'),
  clearTempCache: () => ipcRenderer.invoke('clear-temp-cache'),
  getCacheSize: () => ipcRenderer.invoke('get-cache-size'),
  testProxy: (proxy) => ipcRenderer.invoke('test-proxy', proxy),
  notify: (title, body) => ipcRenderer.invoke('notify', { title, body }),
  getGpus: () => ipcRenderer.invoke('get-gpus'),
  selectVideoFile: () => ipcRenderer.invoke('select-video-file'),
  getVideoFps: (path) => ipcRenderer.invoke('get-video-fps', path),
  aiInterpolate: (args) => ipcRenderer.send('ai-interpolate', args),
  onAIInterpolateProgress: (cb) => ipcRenderer.on('ai-interpolate-progress', (_e, v) => cb(v)),
  onAIInterpolateComplete: (cb) => ipcRenderer.on('ai-interpolate-complete', (_e, v) => cb(v)),
  onAIInterpolateError: (cb) => ipcRenderer.on('ai-interpolate-error', (_e, v) => cb(v)),
  checkForUpdate: () => ipcRenderer.invoke('check-for-update'),
  startUpdateDownload: () => ipcRenderer.invoke('start-update-download'),
  checkToolUpdates: () => ipcRenderer.invoke('check-tool-updates'),
  cancelInstall: () => ipcRenderer.invoke('cancel-install'),
  onUpdaterStatus: (cb) => ipcRenderer.on('updater-status', (_e, v) => cb(v)),
  rpcUpdate: (data) => ipcRenderer.send('rpc-update', data),
  openSniffer: (url) => ipcRenderer.send('open-sniffer', url),
  reportSnifferPage: (info) => ipcRenderer.send('sniffer-page-info', info),
  snifferClearSeen: () => ipcRenderer.send('sniffer-clear-seen'),
  onSnifferCaughtVideo: (cb) => {
    ipcRenderer.on('sniffer-caught-video', (_e, v) => cb(v));
    return () => ipcRenderer.removeAllListeners('sniffer-caught-video');
  },
  onDownloadLog: (cb) => {
    ipcRenderer.on('download-log', (_e, v) => cb(v));
    return () => ipcRenderer.removeAllListeners('download-log');
  },
  getLogFile: () => ipcRenderer.invoke('get-log-file'),
  openChangelog: () => ipcRenderer.invoke('open-changelog'),
  openCrunchyrollSniffer: () => ipcRenderer.send('open-crunchyroll-sniffer'),
  startCrunchyrollDownload: (data) => ipcRenderer.send('start-crunchyroll-download', data),
  onCrunchyrollEpisodeDetected: (cb) => ipcRenderer.on('crunchyroll-episode-detected', (_e, v) => cb(v)),
  onCrunchyrollProgress: (cb) => ipcRenderer.on('crunchyroll-dl-progress', (_e, v) => cb(v)),
  onCrunchyrollComplete: (cb) => ipcRenderer.on('crunchyroll-dl-complete', (_e, v) => cb(v)),
  onCrunchyrollError: (cb) => ipcRenderer.on('crunchyroll-dl-error', (_e, v) => cb(v)),
  onCrunchyrollSnifferStatus: (cb) => ipcRenderer.on('crunchyroll-sniffer-status', (_e, v) => cb(v)),
  selectMediaFile: () => ipcRenderer.invoke('select-media-file'),
  transcribe: (args) => ipcRenderer.send('transcribe', args),
  onTranscribeProgress: (cb) => ipcRenderer.on('transcribe-progress', (_e, v) => cb(v)),
  onTranscribeComplete: (cb) => ipcRenderer.on('transcribe-complete', (_e, v) => cb(v)),
  onTranscribeError: (cb) => ipcRenderer.on('transcribe-error', (_e, v) => cb(v)),

  // ── Topaz Video AI ──
  topazDetect: () => ipcRenderer.invoke('topaz-detect'),
  topazSelectFiles: () => ipcRenderer.invoke('topaz-select-files'),
  topazProbe: (file) => ipcRenderer.invoke('topaz-probe', file),
  topazThumbnail: (file) => ipcRenderer.invoke('topaz-thumbnail', file),
  topazGpus: () => ipcRenderer.invoke('topaz-gpus'),
  topazGpuStats: () => ipcRenderer.invoke('topaz-gpu-stats'),
  topazPreview: (job) => ipcRenderer.invoke('topaz-preview', job),
  topazPresetsLoad: () => ipcRenderer.invoke('topaz-presets-load'),
  topazPresetsSave: (presets) => ipcRenderer.invoke('topaz-presets-save', presets),
  topazQueueLoad: () => ipcRenderer.invoke('topaz-queue-load'),
  topazQueueSave: (queue) => ipcRenderer.invoke('topaz-queue-save', queue),
  topazStart: (job) => ipcRenderer.send('topaz-start', job),
  topazCancel: (id) => ipcRenderer.send('topaz-cancel', id),
  onTopazProgress: (cb) => { ipcRenderer.on('topaz-progress', (_e, v) => cb(v)); return () => ipcRenderer.removeAllListeners('topaz-progress'); },
  onTopazComplete: (cb) => { ipcRenderer.on('topaz-complete', (_e, v) => cb(v)); return () => ipcRenderer.removeAllListeners('topaz-complete'); },
  onTopazError: (cb) => { ipcRenderer.on('topaz-error', (_e, v) => cb(v)); return () => ipcRenderer.removeAllListeners('topaz-error'); },

  // ── Orbit Enhance (moteur libre) ──
  enhanceDetect: () => ipcRenderer.invoke('enhance-detect'),
  enhanceInstall: () => ipcRenderer.invoke('enhance-install'),
  enhanceSelectFiles: () => ipcRenderer.invoke('enhance-select-files'),
  enhanceProbe: (file) => ipcRenderer.invoke('enhance-probe', file),
  enhanceThumbnail: (file) => ipcRenderer.invoke('enhance-thumbnail', file),
  enhanceGpus: () => ipcRenderer.invoke('enhance-gpus'),
  enhanceGpuStats: () => ipcRenderer.invoke('enhance-gpu-stats'),
  enhancePreview: (job) => ipcRenderer.invoke('enhance-preview', job),
  enhancePresetsLoad: () => ipcRenderer.invoke('enhance-presets-load'),
  enhancePresetsSave: (p) => ipcRenderer.invoke('enhance-presets-save', p),
  enhanceQueueLoad: () => ipcRenderer.invoke('enhance-queue-load'),
  enhanceQueueSave: (q) => ipcRenderer.invoke('enhance-queue-save', q),
  enhanceStart: (job) => ipcRenderer.send('enhance-start', job),
  enhanceCancel: (id) => ipcRenderer.send('enhance-cancel', id),
  onEnhanceProgress: (cb) => { ipcRenderer.on('enhance-progress', (_e, v) => cb(v)); return () => ipcRenderer.removeAllListeners('enhance-progress'); },
  onEnhanceComplete: (cb) => { ipcRenderer.on('enhance-complete', (_e, v) => cb(v)); return () => ipcRenderer.removeAllListeners('enhance-complete'); },
  onEnhanceError: (cb) => { ipcRenderer.on('enhance-error', (_e, v) => cb(v)); return () => ipcRenderer.removeAllListeners('enhance-error'); },

  // ── Génération d'image IA (Pollinations · Flux — gratuit) ──
  imageGenModels: () => ipcRenderer.invoke('image-gen-models'),
  imageGenerate: (params) => ipcRenderer.invoke('image-gen', params),

  // ── Gomme magique IA · suppression d'objet (LaMa — local & gratuit) ──
  inpaintDetect: () => ipcRenderer.invoke('inpaint-detect'),
  inpaintInstall: () => ipcRenderer.invoke('inpaint-install'),
  inpaintRun: (params) => ipcRenderer.invoke('inpaint-run', params),
  onInpaintProgress: (cb) => { const h = (_e, v) => cb(v); ipcRenderer.on('inpaint-progress', h); return () => ipcRenderer.removeListener('inpaint-progress', h); },

  // ── Sélection intelligente (SAM — clic → masque) ──
  samDetect: () => ipcRenderer.invoke('sam-detect'),
  samEmbed: (params) => ipcRenderer.invoke('sam-embed', params),
  samPoints: (params) => ipcRenderer.invoke('sam-points', params),
  onSamProgress: (cb) => { const h = (_e, v) => cb(v); ipcRenderer.on('sam-progress', h); return () => ipcRenderer.removeListener('sam-progress', h); },
  yoloDetect: (params) => ipcRenderer.invoke('yolo-detect', params),

  // ── HandBrake ──
  hbDetect: () => ipcRenderer.invoke('hb-detect'),
  hbInstall: () => ipcRenderer.invoke('hb-install'),
  hbQueueLoad: () => ipcRenderer.invoke('hb-queue-load'),
  hbQueueSave: (q) => ipcRenderer.invoke('hb-queue-save', q),
  hbPresetsLoad: () => ipcRenderer.invoke('hb-presets-load'),
  hbPresetsSave: (p) => ipcRenderer.invoke('hb-presets-save', p),
  hbStart: (job) => ipcRenderer.send('hb-start', job),
  hbCancel: (id) => ipcRenderer.send('hb-cancel', id),
  onHbProgress: (cb) => { ipcRenderer.on('hb-progress', (_e, v) => cb(v)); return () => ipcRenderer.removeAllListeners('hb-progress'); },
  onHbComplete: (cb) => { ipcRenderer.on('hb-complete', (_e, v) => cb(v)); return () => ipcRenderer.removeAllListeners('hb-complete'); },
  onHbError: (cb) => { ipcRenderer.on('hb-error', (_e, v) => cb(v)); return () => ipcRenderer.removeAllListeners('hb-error'); },

  // ── Médiathèque (Anime Media Manager) ──
  libLoad: () => ipcRenderer.invoke('lib-load'),
  libSave: (data) => ipcRenderer.invoke('lib-save', data),
  libAddFiles: () => ipcRenderer.invoke('lib-add-files'),
  libScanFolder: () => ipcRenderer.invoke('lib-scan-folder'),
  libProbe: (file) => ipcRenderer.invoke('lib-probe', file),
  libThumbnail: (file) => ipcRenderer.invoke('lib-thumbnail', file),
  libParseName: (name) => ipcRenderer.invoke('lib-parse-name', name),
  libPresets: () => ipcRenderer.invoke('lib-presets'),
  libConvert: (job) => ipcRenderer.send('lib-convert', job),
  libCancel: (id) => ipcRenderer.send('lib-cancel', id),
  onLibConvertProgress: (cb) => { ipcRenderer.on('lib-convert-progress', (_e, v) => cb(v)); return () => ipcRenderer.removeAllListeners('lib-convert-progress'); },
  onLibConvertComplete: (cb) => { ipcRenderer.on('lib-convert-complete', (_e, v) => cb(v)); return () => ipcRenderer.removeAllListeners('lib-convert-complete'); },
  onLibConvertError: (cb) => { ipcRenderer.on('lib-convert-error', (_e, v) => cb(v)); return () => ipcRenderer.removeAllListeners('lib-convert-error'); },

  // ── Suppression de fond IA (Robust Video Matting) ──
  mattingDetect: () => ipcRenderer.invoke('matting-detect'),
  mattingInstall: (modelKey) => ipcRenderer.invoke('matting-install', modelKey),
  mattingPreview: (job) => ipcRenderer.invoke('matting-preview', job),
  mattingStart: (job) => ipcRenderer.send('matting-start', job),
  mattingCancel: (id) => ipcRenderer.send('matting-cancel', id),
  onMattingProgress: (cb) => { ipcRenderer.on('matting-progress', (_e, v) => cb(v)); return () => ipcRenderer.removeAllListeners('matting-progress'); },
  onMattingComplete: (cb) => { ipcRenderer.on('matting-complete', (_e, v) => cb(v)); return () => ipcRenderer.removeAllListeners('matting-complete'); },
  onMattingError: (cb) => { ipcRenderer.on('matting-error', (_e, v) => cb(v)); return () => ipcRenderer.removeAllListeners('matting-error'); },

  // ── Discloud (stockage de fichiers sur Discord · webhook + AES) ──
  discloudStatus: () => ipcRenderer.invoke('discloud-status'),
  discloudSetup: (data) => ipcRenderer.invoke('discloud-setup', data),
  discloudUnlock: (data) => ipcRenderer.invoke('discloud-unlock', data),
  discloudLock: () => ipcRenderer.invoke('discloud-lock'),
  discloudIndex: () => ipcRenderer.invoke('discloud-index'),
  discloudMkdir: (data) => ipcRenderer.invoke('discloud-mkdir', data),
  discloudRename: (data) => ipcRenderer.invoke('discloud-rename', data),
  discloudPickFiles: () => ipcRenderer.invoke('discloud-pick-files'),
  discloudUpload: (data) => ipcRenderer.invoke('discloud-upload', data),
  discloudDownload: (data) => ipcRenderer.invoke('discloud-download', data),
  discloudDelete: (data) => ipcRenderer.invoke('discloud-delete', data),
  discloudCancel: (jobId) => ipcRenderer.send('discloud-cancel', jobId),
  onDiscloudProgress: (cb) => { ipcRenderer.on('discloud-progress', (_e, v) => cb(v)); return () => ipcRenderer.removeAllListeners('discloud-progress'); },

  // ── Discloud Cloud (Drive via serveur + comptes) ──
  cloudStatus: () => ipcRenderer.invoke('discloud-cloud-status'),
  cloudSetServer: (data) => ipcRenderer.invoke('discloud-cloud-set-server', data),
  cloudRegister: (data) => ipcRenderer.invoke('discloud-cloud-register', data),
  cloudLogin: (data) => ipcRenderer.invoke('discloud-cloud-login', data),
  cloudLogout: () => ipcRenderer.invoke('discloud-cloud-logout'),
  // Stockage Telegram (MTProto, compte perso, sans bot)
  tgStatus: () => ipcRenderer.invoke('discloud-tg-status'),
  tgSetApi: (data) => ipcRenderer.invoke('discloud-tg-set-api', data),
  tgSendCode: (data) => ipcRenderer.invoke('discloud-tg-send-code', data),
  tgSignIn: (data) => ipcRenderer.invoke('discloud-tg-sign-in', data),
  tgSignInPassword: (data) => ipcRenderer.invoke('discloud-tg-sign-in-password', data),
  tgLogout: () => ipcRenderer.invoke('discloud-tg-logout'),
  // Drop : partage sans compte (code)
  dropUpload: (data) => ipcRenderer.invoke('discloud-drop-upload', data),
  dropDownload: (data) => ipcRenderer.invoke('discloud-drop-download', data),
  cloudServerInfo: () => ipcRenderer.invoke('discloud-cloud-server-info'),
  cloudForgot: (data) => ipcRenderer.invoke('discloud-cloud-forgot', data),
  cloudReset: (data) => ipcRenderer.invoke('discloud-cloud-reset', data),
  cloudCryptoStatus: () => ipcRenderer.invoke('discloud-cloud-crypto-status'),
  cloudSetupCrypto: (data) => ipcRenderer.invoke('discloud-cloud-setup-crypto', data),
  cloudUnlock: (data) => ipcRenderer.invoke('discloud-cloud-unlock', data),
  cloudNodes: () => ipcRenderer.invoke('discloud-cloud-nodes'),
  cloudMkdir: (data) => ipcRenderer.invoke('discloud-cloud-mkdir', data),
  cloudRename: (data) => ipcRenderer.invoke('discloud-cloud-rename', data),
  cloudDelete: (data) => ipcRenderer.invoke('discloud-cloud-delete', data),
  cloudUpload: (data) => ipcRenderer.invoke('discloud-cloud-upload', data),
  cloudDownload: (data) => ipcRenderer.invoke('discloud-cloud-download', data),
  // Admin (profils + webhooks)
  cloudAdminProfiles: () => ipcRenderer.invoke('discloud-cloud-admin-profiles'),
  cloudAdminCreateProfile: (data) => ipcRenderer.invoke('discloud-cloud-admin-create-profile', data),
  cloudAdminActivateProfile: (data) => ipcRenderer.invoke('discloud-cloud-admin-activate-profile', data),
  cloudAdminDeleteProfile: (data) => ipcRenderer.invoke('discloud-cloud-admin-delete-profile', data),
  cloudAdminWebhooks: (data) => ipcRenderer.invoke('discloud-cloud-admin-webhooks', data),
  cloudAdminAddWebhook: (data) => ipcRenderer.invoke('discloud-cloud-admin-add-webhook', data),
  cloudAdminToggleWebhook: (data) => ipcRenderer.invoke('discloud-cloud-admin-toggle-webhook', data),
  cloudAdminDeleteWebhook: (data) => ipcRenderer.invoke('discloud-cloud-admin-delete-webhook', data),

  // ── Licence Premium ──
  licenseStatus: () => ipcRenderer.invoke('license-status'),
  licenseActivate: (key) => ipcRenderer.invoke('license-activate', { key }),
  licenseDeactivate: () => ipcRenderer.invoke('license-deactivate'),
  licenseCheckout: () => ipcRenderer.invoke('license-checkout'),
  licenseSync: () => ipcRenderer.invoke('license-sync'),
  licenseAdminList: () => ipcRenderer.invoke('license-admin-list'),
  licenseAdminGrant: (email) => ipcRenderer.invoke('license-admin-grant', { email }),
  licenseAdminRevoke: (email) => ipcRenderer.invoke('license-admin-revoke', { email }),
  licenseAdminRevokeKey: (keyId) => ipcRenderer.invoke('license-admin-revoke-key', { keyId }),
  licenseAdminUnrevokeKey: (keyId) => ipcRenderer.invoke('license-admin-unrevoke-key', { keyId }),
  licenseAdminResetDevice: (email) => ipcRenderer.invoke('license-admin-reset-device', { email }),
  licenseAdminGenKey: (email) => ipcRenderer.invoke('license-admin-genkey', { email }),
  licenseAdminPayments: () => ipcRenderer.invoke('license-admin-payments'),
  licenseAdminDeleteUser: (email) => ipcRenderer.invoke('license-admin-delete-user', { email }),
  licenseAdminGrantDevice: (device, note) => ipcRenderer.invoke('license-admin-grant-device', { device, note }),
  licenseAdminRevokeDevice: (device) => ipcRenderer.invoke('license-admin-revoke-device', { device }),
  licenseAdminDevices: () => ipcRenderer.invoke('license-admin-devices'),
  licenseDeviceId: () => ipcRenderer.invoke('license-device-id'),
  onLicenseRevoked: (cb) => { const h = () => cb(); ipcRenderer.on('license-revoked', h); return () => ipcRenderer.removeListener('license-revoked', h); },
  reportBug: (description, context) => ipcRenderer.invoke('report-bug', { description, context }),
  reportError: (payload) => ipcRenderer.send('report-error', payload),
  licenseClaimDevice: () => ipcRenderer.invoke('license-claim-device'),

  // ── AI Assistant ──
  aiChat: (data) => ipcRenderer.invoke('ai-chat', data),
  llmStatus: () => ipcRenderer.invoke('llm-status'),
  llmInstall: () => ipcRenderer.invoke('llm-install'),
  onLlmProgress: (cb) => { ipcRenderer.on('llm-progress', (_e, v) => cb(v)); return () => ipcRenderer.removeAllListeners('llm-progress'); },
});
